name: Deployment Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use only one version for deployment

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build

    - name: Deploy to Ubuntu Server
      if: success()
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.USERNAME }}
        SERVER_IP: ${{ secrets.HOST }}
        PROJECT_PATH: "/var/www/html/dms-zmnet"
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
          cd $PROJECT_PATH
          git pull origin main
          npm ci
          npm run build
          pm2 restart nextjs-app || pm2 start npm --name "dms-zamnet" -- run start
        EOF
